if(NOT DEFINED ROOT)
    message(FATAL_ERROR "no-zz source assertion is missing ROOT")
endif()

cmake_policy(SET CMP0009 NEW)
file(GLOB_RECURSE entries LIST_DIRECTORIES false "${ROOT}/*")
list(FILTER entries EXCLUDE REGEX "/build/go-foundation-v2/")
list(FILTER entries EXCLUDE REGEX "/\\.git/")
list(FILTER entries INCLUDE REGEX "/zz[^/]*$")
if(entries)
    list(JOIN entries "\n" listed_entries)
    message(FATAL_ERROR "Foundation sources must not use names beginning with zz:\n${listed_entries}")
endif()
