stateDiagram-v2
    Draft --> Cancelled : Cancel
    Draft --> Submitted : Submit
    Submitted --> Cancelled : Cancel
    Submitted --> Expired : Expire after 60.seconds
    Submitted --> Paid : Pay
